# Generated by Django 3.2.13 on 2022-09-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlyRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entities', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_text', models.TextField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_innovation.onlyfile')),
            ],
        ),
        migrations.CreateModel(
            name='FilesUploadedPerReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_innovation.onlyfile')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_innovation.onlyrequest')),
            ],
        ),
    ]
